const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const outDir=process.env.VALIDATION_OUTPUT || path.join(require('os').tmpdir(),'grimes-validation');fs.mkdirSync(outDir,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.CHROME_EXECUTABLE ? {executablePath:process.env.CHROME_EXECUTABLE}:{}),args:['--enable-webgl','--ignore-gpu-blocklist']});
try{const page=await browser.newPage({viewport:{width:1440,height:1000},ignoreHTTPSErrors:true});page.setDefaultTimeout(240000);const errors=[];page.on('crash',()=>console.log('PAGE_CRASH'));browser.on('disconnected',()=>console.log('BROWSER_DISCONNECTED'));page.on('pageerror',e=>{errors.push(e.message);console.log('PAGEERROR',e.message)});
await page.route('**/grimes-bim-viewer.html',route=>{let s=fs.readFileSync(path.join(__dirname,'../grimes-bim-viewer.html'),'utf8');s=s.replace(/<\/script>\s*<\/body>/,`window.__audit={renderer,scene,camera,layerState,LAYERS,get meshes(){return equipMeshes},get meta(){return equipMeta},get picked(){return equipPicked},pick:pickEquipment,resolveElementHit,findElementSelection,raycaster,THREE};\n</script>\n</body>`);return route.fulfill({contentType:'text/html',body:s})});
await page.route('**/data/data/building_data.json',route=>route.fulfill({json:{meters:Object.fromEntries(['3','76','77'].map(id=>[id,{latest:{kw:100,t:new Date().toISOString()},timeseries_kw:[]}]))}}));
await page.goto((process.env.VIEWER_BASE_URL || 'http://127.0.0.1:8765')+'/grimes-bim-viewer.html',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.__audit);console.log('READY recovered');
await page.getByRole('button',{name:'Got it — let me explore'}).click();
const results=[];for(const key of ['equipment','fixtures','lighting','lifesafety','structural','conduit','duct','hydronic','plumbing','fire']){
 const start=Date.now();await page.evaluate(k=>toggleLayer(k),key);await page.waitForFunction(k=>window.__audit.layerState[k]?.group&&!window.__audit.layerState[k].loading,key);
 const r=await page.evaluate(k=>{const a=window.__audit,st=a.layerState[k],ids=new Set(st.meshes.flatMap(m=>m.userData.ids)),expected=Object.entries(a.meta).filter(([id,e])=>e.layer===k).map(([id])=>id);return{key:k,stats:st.renderStats,expected:expected.length,renderIds:ids.size,missing:expected.filter(id=>!ids.has(id)).length,binding:st.identityBinding,heap:performance.memory?.usedJSHeapSize}},key);r.loadMs=Date.now()-start;results.push(r);console.log(JSON.stringify(r));assert.equal(r.missing,0);assert.equal(r.stats.unidentifiedObjects,0);assert.equal(r.stats.sourceTriangles,r.stats.renderTriangles);assert.equal(r.stats.sourceSegments,r.stats.renderSegments);
 await page.evaluate(k=>{const a=window.__audit,id=Object.keys(a.meta).find(id=>a.meta[id].layer===k);selectElementById(id);},key);await page.waitForTimeout(30);const selected=await page.evaluate(()=>({id:window.__audit.picked.id,source:document.getElementById('twinDetInfo').textContent}));assert.ok(selected.source.includes(key==='equipment'?'elements.json':key+'.elements.json'));
}
const all=await page.evaluate(()=>{const a=window.__audit;a.renderer.render(a.scene,a.camera);return {drawCalls:a.renderer.info.render.calls,triangles:a.renderer.info.render.triangles,geometries:a.renderer.info.memory.geometries,elementBatches:a.meshes.length}});console.log('ALL',JSON.stringify(all));
await page.evaluate(()=>{setElementFloor('L1');document.getElementById('elementFloor').value='L1';toggleLayersMenu()});
assert.equal(await page.evaluate(()=>window.__audit.meshes.some(m=>m.visible&&m.userData.levelKey!=='L1')),false);
const rayProof=await page.evaluate(()=>{const a=window.__audit,T=a.THREE;for(const mesh of a.meshes){if(!mesh.visible||mesh.isLine||mesh.isInstancedMesh)continue;const g=mesh.geometry,p=g.attributes.position,ix=g.index;if(!ix||ix.count<3)continue;const A=new T.Vector3().fromBufferAttribute(p,ix.getX(0)),B=new T.Vector3().fromBufferAttribute(p,ix.getX(1)),C=new T.Vector3().fromBufferAttribute(p,ix.getX(2)),normal=new T.Vector3().subVectors(B,A).cross(new T.Vector3().subVectors(C,A)).normalize();if(normal.lengthSq()===0)continue;const center=A.clone().add(B).add(C).multiplyScalar(1/3),ray=new T.Raycaster(center.clone().addScaledVector(normal,.01),normal.clone().negate(),0,.1),hit=ray.intersectObject(mesh,false)[0];if(!hit)continue;const id=a.resolveElementHit(hit.object,hit.instanceId,hit.faceIndex,hit.index);if(id){a.pick(mesh,hit.instanceId,id);return{id,layer:mesh.userData.layer}}}return null});assert.ok(rayProof);console.log('REAL_RAY_PICK',rayProof);
await page.screenshot({path:path.join(outDir,'recovered-desktop.png')});
// Carbon form uses an explicitly entered scenario, never a built-in factor.
await page.evaluate(()=>{const a=window.__audit,id=Object.keys(a.meta).find(id=>a.meta[id].layer==='structural'&&a.meta[id].structural_material&&a.meta[id].volume);selectElementById(id);document.getElementById('twinDetails').classList.add('open');});
if(await page.locator('#carbonFactor').count()){await page.locator('#carbonFactor').evaluate(e=>e.value='100');await page.locator('#carbonSource').evaluate(e=>e.value='QA scenario, not a project EPD');await page.evaluate(()=>document.getElementById('carbonForm').requestSubmit());assert.match(await page.locator('#carbonResult').textContent(),/MODELLED scenario/)}
await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(outDir,'recovered-mobile.png')});
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth),false);assert.deepEqual(errors,[]);
fs.writeFileSync(path.join(outDir,'recovered-browser.json'),JSON.stringify({results,all,rayProof,errors},null,2));console.log('PASS recovered full browser');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
