const fs=require('node:fs'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const out=process.env.VALIDATION_OUTPUT||require('node:path').join(require('node:os').tmpdir(),'grimes-mobile-validation');fs.mkdirSync(out,{recursive:true});
const base=process.env.VIEWER_BASE_URL||'https://doe2park.github.io/Graduate-Project/';
(async()=>{const b=await chromium.launch({headless:true,executablePath:process.env.CHROME_EXECUTABLE||undefined});try{
 const c=await b.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.route('**/grimes-bim-viewer.html*',async route=>{const response=await route.fetch();let html=process.env.STAGED_DIR?fs.readFileSync(process.env.STAGED_DIR+'/grimes-bim-viewer.html','utf8'):await response.text();html=html.replace('let _lastT = 0;',`window.__mobileAudit=()=>({walkMode,pos:camera.position.toArray(),quat:camera.quaternion.toArray(),keys:{...keys},aimedElementId,layer:layerState.equipment?.renderStats});let _lastT = 0;`);await route.fulfill({response,body:html});});
 await p.goto(base.replace(/\/$/,'')+'/grimes-bim-viewer.html');await p.waitForFunction(()=>window.__mobileAudit&&getComputedStyle(document.querySelector('#loading')).display==='none',null,{timeout:90000});await p.getByRole('button',{name:'Got it — let me explore'}).tap();
 assert.equal(await p.locator('#layersMenu').isVisible(),false,'layers menu respects hidden');await p.locator('#layersBtn').tap();assert.equal(await p.locator('#layersMenu').isVisible(),true);await p.locator('#layersMenu button[title="Close"]').tap();assert.equal(await p.locator('#layersMenu').isVisible(),false);
 assert.equal(await p.locator('#walkBtn').isVisible(),true,'mobile Walk available');await p.locator('#walkBtn').tap();await p.waitForFunction(()=>__mobileAudit().walkMode);assert.equal(await p.locator('#crosshair').isVisible(),true);const before=await p.evaluate(()=>__mobileAudit());
 const cd=await c.newCDPSession(p),rect=await p.locator('[data-walk-key="KeyW"]').boundingBox();await cd.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:rect.x+rect.width/2,y:rect.y+rect.height/2,id:1}]});await p.waitForTimeout(350);await cd.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await p.waitForTimeout(200);const moved=await p.evaluate(()=>__mobileAudit());assert.ok(Math.hypot(...moved.pos.map((v,i)=>v-before.pos[i]))>.15,'touch hold moves camera');assert.equal(moved.keys.KeyW,false,'release stops movement');
 await cd.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:230,y:340,id:2}]});await cd.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:300,y:375,id:2}]});await cd.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});const looked=await p.evaluate(()=>__mobileAudit());assert.notDeepEqual(looked.quat,moved.quat,'drag changes view direction');
 await p.setViewportSize({width:844,height:390});assert.equal(await p.locator('#mobileWalkPad').isVisible(),true,'Walk controls survive landscape');await p.setViewportSize({width:390,height:844});await p.locator('#mobileWalkExit').tap();const exited=await p.evaluate(()=>__mobileAudit());assert.equal(exited.walkMode,false);assert.ok(Math.hypot(...looked.pos.map((v,i)=>v-exited.pos[i]))<.1,'exit preserves viewpoint');
 await p.locator('#mobileBrowse').tap();await p.locator('#mobileElementSearch').fill('203987');await p.locator('#mobileElementResults button[data-element-id="203987"]').tap();await p.waitForFunction(()=>document.getElementById('twinDetInfo').textContent.includes('203987'));assert.match(await p.locator('#twinDetInfo').innerText(),/elements.json/);assert.equal(await p.locator('#mobileElementBrowser').isVisible(),false);await p.waitForFunction(()=>!document.getElementById('twinBadge').textContent.includes('LOADING'),null,{timeout:30000});await p.screenshot({path:out+'/mobile-element.png'});
 await p.setViewportSize({width:844,height:390});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'landscape has no page overflow');
 const perf=await c.newPage();if(process.env.STAGED_DIR)await perf.route('**/grimes-performance.html*',async route=>{const r=await route.fetch();await route.fulfill({response:r,body:fs.readFileSync(process.env.STAGED_DIR+'/grimes-performance.html','utf8')});});await perf.goto(base.replace(/\/$/,'')+'/grimes-performance.html');await perf.waitForSelector('#dailyBox svg');assert.equal(await perf.evaluate(()=>innerWidth),390,'performance uses device viewport');assert.equal(await perf.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await perf.locator('#dailyBox').scrollIntoViewIfNeeded();const chart=await perf.locator('#dailyBox').boundingBox(),pcd=await c.newCDPSession(perf);await pcd.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:chart.x+chart.width-30,y:chart.y+80,id:3}]});for(let i=1;i<=8;i++){await pcd.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:chart.x+chart.width-30-i*20,y:chart.y+80,id:3}]});await perf.waitForTimeout(25);}await pcd.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.ok(await perf.locator('#dailyBox').evaluate(e=>e.scrollLeft)>0,'touch swipes wide charts horizontally');await perf.getByText('Monthly table',{exact:true}).tap();assert.ok(await perf.locator('#mtable tr').count()>1);await perf.screenshot({path:out+'/mobile-performance.png'});assert.deepEqual(errors,[]);console.log('PASS: mobile menu, Walk hold/release, drag look, retained exit, searchable source-ID selection, portrait/landscape and performance tables');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
