import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {pathToFileURL} from 'node:url';
const THREE = await import(process.env.THREE_MODULE ? pathToFileURL(process.env.THREE_MODULE).href : 'three');
const html=fs.readFileSync(new URL('../grimes-bim-viewer.html',import.meta.url),'utf8');
const source=html.slice(html.indexOf('/* GLTFLoader uniquifies'),html.indexOf('/* ELEMENT DATA HELPERS */'));
const ctx = vm.createContext({ console, setTimeout }); vm.runInContext(source,ctx);
const build = (...args) => { assert.equal(typeof ctx.buildElementRenderTier,'function','render tier must exist'); return ctx.buildElementRenderTier(THREE,...args); };
const mat = new THREE.MeshStandardMaterial({ color: 0x80a0c0, transparent:true, opacity:0.65 });
const meta = {a:{levelKey:'L1',type:'pipe'},b:{levelKey:'L1',type:'pipe'},c:{levelKey:'L2',type:'pipe'},d:{levelKey:'L1',type:'duct'}};
function triangle(){const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute([0,0,0,1,0,0,0,1,0],3));g.setAttribute('normal',new THREE.Float32BufferAttribute([0,0,1,0,0,1,0,0,1],3));g.setAttribute('uv',new THREE.Float32BufferAttribute([0,0,1,0,0,1],2));g.setIndex([0,1,2]);return g;}
function add(scene,id,g,x=0,scale=1){const o=new THREE.Mesh(g,mat);o.name=id;o.position.x=x;o.scale.x=scale;scene.add(o);return o;}
function hit(scene,x,y=.2){scene.updateMatrixWorld(true);return new THREE.Raycaster(new THREE.Vector3(x,y,2),new THREE.Vector3(0,0,-1)).intersectObjects(scene.children,true)[0];}
function resolve(h){assert.ok(h,'expected ray hit');return ctx.resolveElementHit(h.object,h.instanceId,h.faceIndex,h.index);}
test('merges unique fragments, preserves material, UVs, triangles and world-space identity',async()=>{
 const s=new THREE.Group();s.position.x=10;add(s,'a',triangle());add(s,'b',triangle(),2);s.updateMatrixWorld(true);
 const before=s.children[0].geometry.attributes.position.array.slice();const r=await build(s,meta,'fire');assert.equal(r.meshes.length,1);assert.equal(r.meshes[0].geometry.index.count,6);assert.equal(r.stats.sourceTriangles,2);assert.equal(r.stats.renderTriangles,2);
 const m=r.meshes[0];assert.equal(m.material.opacity,.65);assert.equal(m.material.color.getHex(),mat.color.getHex());assert.equal(m.geometry.attributes.uv.count,6);assert.deepEqual([...before],[...s.children[0].geometry.attributes.position.array]);
 const out=new THREE.Group();out.add(...r.meshes);assert.equal(resolve(hit(out,10.2)),'a');assert.equal(resolve(hit(out,12.2)),'b');assert.equal(ctx.resolveElementHit(m,undefined,2,undefined),null);
});
test('mirrored transform retains front-face picks and correctly transformed normals',async()=>{const s=new THREE.Group();add(s,'a',triangle(),0,-2);s.updateMatrixWorld(true);const r=await build(s,meta,'x');const out=new THREE.Group();out.add(...r.meshes);assert.equal(resolve(hit(out,-.4)),'a');assert.equal(r.meshes[0].geometry.attributes.normal.getZ(0),1);});
test('partitioned levels and types filter without mutating transforms; highlight restores source colors',async()=>{const s=new THREE.Group();for(const [i,id]of ['a','b','c','d'].entries())add(s,id,triangle(),i*2);s.updateMatrixWorld(true);const r=await build(s,meta,'x');assert.equal(r.meshes.length,3);for(const m of r.meshes)ctx.setElementRenderVisible(m,'L1','pipe',meta);assert.equal(r.meshes.filter(m=>m.visible).length,1);const m=r.meshes.find(m=>m.visible);const before=m.geometry.attributes.color.array.slice();ctx.highlightElementRender(m,'a',true,new THREE.Color(0xffbb22));assert.notDeepEqual([...m.geometry.attributes.color.array],[...before]);assert.deepEqual([...m.geometry.attributes.color.array.slice(9)],[...before.slice(9)]);ctx.highlightElementRender(m,'a',false);assert.deepEqual([...m.geometry.attributes.color.array],[...before]);assert.equal(ctx.findElementSelection(m,'b').faceIndex,1);});
test('substantially reused geometry stays instanced and IDs/highlight survive',async()=>{const s=new THREE.Group(),g=triangle();for(let i=0;i<8;i++)add(s,i%2?'b':'a',g,i*2);s.updateMatrixWorld(true);const r=await build(s,meta,'x');assert.equal(r.meshes.length,1);const m=r.meshes[0];assert.equal(m.isInstancedMesh,true);assert.equal(m.count,8);const out=new THREE.Group();out.add(m);assert.equal(resolve(hit(out,2.2)),'b');ctx.highlightElementRender(m,'b',true,new THREE.Color(0xffbb22));let c=new THREE.Color();m.getColorAt(1,c);assert.equal(c.getHex(),0xffbb22);m.getColorAt(0,c);assert.equal(c.getHex(),0xffffff);ctx.highlightElementRender(m,'b',false);m.getColorAt(1,c);assert.equal(c.getHex(),0xffffff);});
test('line strips become merged segments, all identities remain ray-pickable',async()=>{const s=new THREE.Group();for(const [i,id]of ['a','b'].entries()){const g=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(0,0,0),new THREE.Vector3(1,0,0),new THREE.Vector3(1,1,0)]);const o=new THREE.Line(g,new THREE.LineBasicMaterial({color:0x778899}));o.material= i?s.children[0].material:o.material;o.name=id;o.position.x=i*3;s.add(o);}s.updateMatrixWorld(true);const r=await build(s,meta,'x');assert.equal(r.meshes.length,1);const m=r.meshes[0];assert.equal(m.isLineSegments,true);assert.equal(m.geometry.index.count,8);const out=new THREE.Group();out.add(m);out.updateMatrixWorld(true);const ray=new THREE.Raycaster(new THREE.Vector3(3.5,0,2),new THREE.Vector3(0,0,-1));ray.params.Line.threshold=.02;assert.equal(resolve(ray.intersectObjects(out.children)[0]),'b');assert.equal(ctx.findElementSelection(m,'b').index,3);});
test('material groups, ancestor identity, normalized vertex colors and alpha survive',async()=>{
 const s=new THREE.Group(),element=new THREE.Group();element.name='a';s.add(element);
 const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute([0,0,0,1,0,0,0,1,0,2,0,0,3,0,0,2,1,0],3));g.setAttribute('color',new THREE.Uint8BufferAttribute([255,128,0,128,255,128,0,128,255,128,0,128,0,128,255,255,0,128,255,255,0,128,255,255],4,true));g.setIndex([0,1,2,3,4,5]);g.addGroup(0,3,0);g.addGroup(3,3,1);
 const m1=new THREE.MeshBasicMaterial({vertexColors:true,color:0xffffff}),m2=new THREE.MeshBasicMaterial({vertexColors:true,color:0xaabbcc,opacity:.4,transparent:true});element.add(new THREE.Mesh(g,[m1,m2]));s.updateMatrixWorld(true);
 const r=await build(s,meta,'x');assert.equal(r.meshes.length,2);assert.equal(r.stats.renderTriangles,2);assert.equal(r.meshes[0].geometry.attributes.position.count,3);assert.ok(Math.abs(r.meshes[0].geometry.attributes.color.getW(0)-128/255)<1e-6);assert.equal(r.meshes[1].material.color.getHex(),0xaabbcc);
 const out=new THREE.Group();out.add(...r.meshes);assert.equal(resolve(hit(out,2.2)),'a');const color=r.meshes[0].geometry.attributes.color;const before=color.array.slice();ctx.highlightElementRender(r.meshes[0],'a',true,new THREE.Color('red'));assert.equal(color.getW(0),before[3]);ctx.highlightElementRender(r.meshes[0],'a',false);assert.deepEqual([...color.array],[...before]);
});
test('indexed draw ranges preserve triangle counts and discard out-of-range faces',async()=>{const s=new THREE.Group();const g=triangle();g.setIndex([0,1,2,0,2,1]);g.setDrawRange(3,3);add(s,'a',g);s.updateMatrixWorld(true);const r=await build(s,meta,'x');assert.equal(r.stats.sourceTriangles,1);assert.equal(r.stats.renderTriangles,1);assert.equal(r.meshes[0].geometry.index.count,3);});
test('bounded chunks keep large collections pickable with exact triangle totals',async()=>{const s=new THREE.Group();for(let i=0;i<4;i++){const g=new THREE.BufferGeometry(),p=new Float32Array(60000*3);for(let n=0;n<20000;n++)p.set([i*2,0,0,i*2+1,0,0,i*2,1,0],n*9);g.setAttribute('position',new THREE.BufferAttribute(p,3));add(s,i%2?'b':'a',g);}s.updateMatrixWorld(true);const r=await build(s,meta,'x');assert.equal(r.meshes.length,2);assert.equal(r.stats.sourceTriangles,80000);assert.equal(r.stats.renderTriangles,80000);assert.ok(r.meshes.every(m=>m.geometry.attributes.position.count<=180000));assert.ok(r.meshes.every(m=>ctx.findElementSelection(m,'b')));});
test('a single oversized fragment splits on primitive boundaries while retaining identity',async()=>{const s=new THREE.Group(),g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(new Float32Array(180003*3),3));add(s,'a',g);s.updateMatrixWorld(true);const r=await build(s,meta,'x');assert.equal(r.meshes.length,2);assert.equal(r.stats.renderTriangles,60001);assert.ok(r.meshes.every(m=>m.geometry.attributes.position.count<=180000));assert.ok(r.meshes.every(m=>ctx.findElementSelection(m,'a')));});
test('unused source color attributes do not tint materials that disabled vertex colors',async()=>{const s=new THREE.Group(),g=triangle();g.setAttribute('color',new THREE.Float32BufferAttribute([1,0,0,1,0,0,1,0,0],3));const o=add(s,'a',g);o.material=new THREE.MeshBasicMaterial({color:0xffffff,vertexColors:false});s.updateMatrixWorld(true);const r=await build(s,meta,'x');assert.equal(r.meshes[0].geometry.attributes.color.getY(0),1);assert.equal(g.attributes.color.getY(0),0);});
test('GLTFLoader duplicate names retain exact source IDs through parser associations',async()=>{
 const {GLTFLoader}=await import(process.env.THREE_MODULE ? pathToFileURL(process.env.THREE_MODULE.replace('/build/three.module.js','/examples/jsm/loaders/GLTFLoader.js')).href : 'three/addons/loaders/GLTFLoader.js');
 globalThis.ProgressEvent ||= class ProgressEvent {constructor(type,init={}){this.type=type;Object.assign(this,init);}};
 const positions=new Float32Array([0,0,0,1,0,0,0,1,0]),buffer=Buffer.from(positions.buffer);
 const json={asset:{version:'2.0'},scene:0,scenes:[{nodes:[0,1,2]}],nodes:[{name:'a',mesh:0},{name:'a',mesh:0,translation:[2,0,0]},{name:'a_1',mesh:0,translation:[4,0,0]}],meshes:[{primitives:[{attributes:{POSITION:0}}]}],buffers:[{byteLength:buffer.length,uri:'data:application/octet-stream;base64,'+buffer.toString('base64')}],bufferViews:[{buffer:0,byteLength:buffer.length}],accessors:[{bufferView:0,componentType:5126,count:3,type:'VEC3',min:[0,0,0],max:[1,1,0]}]};
 const gltf=await new GLTFLoader().parseAsync(JSON.stringify(json),'');
 assert.notEqual(gltf.scene.children[0].name,gltf.scene.children[1].name);
 assert.equal(typeof ctx.bindElementSourceIds,'function','bind original names before merging');
 const bound=ctx.bindElementSourceIds(gltf);assert.equal(bound.boundNodes,3);assert.equal(bound.associationNameConflicts,2);
 const localMeta={a:{levelKey:'L1',type:'pipe'},a_1:{levelKey:'L1',type:'pipe'}};
 gltf.scene.updateMatrixWorld(true);const r=await build(gltf.scene,localMeta,'x');const out=new THREE.Group();out.add(...r.meshes);
 assert.equal(resolve(hit(out,.2)),'a');assert.equal(resolve(hit(out,2.2)),'a');assert.equal(resolve(hit(out,4.2)),'a_1');assert.equal(r.stats.unidentifiedObjects,0);
});
test('unidentified geometry remains visible but is explicitly counted',async()=>{const s=new THREE.Group();add(s,'missing-id',triangle());s.updateMatrixWorld(true);const r=await build(s,meta,'x');assert.equal(r.stats.unidentifiedObjects,1);assert.equal(r.stats.sourceObjects,1);assert.equal(r.stats.renderTriangles,1);assert.equal(r.meshes.length,1);assert.deepEqual([...r.stats.unidentifiedNames],['missing-id']);});
test('source cleanup releases loader roots while preserving live instanced geometry and picks',async()=>{const s=new THREE.Group(),g=triangle();for(let i=0;i<8;i++)add(s,i%2?'b':'a',g,i*2);s.updateMatrixWorld(true);const r=await build(s,meta,'x');const associations=new Map(s.children.map((o,i)=>[o,{nodes:i}]));let cleared=false;const gltf={scene:s,scenes:[s],parser:{cache:{removeAll(){cleared=true;}},associations}};assert.equal(typeof ctx.releaseElementSource,'function','source cleanup helper must exist');ctx.releaseElementSource(gltf);assert.equal(gltf.scene,null);assert.equal(gltf.parser,null);assert.equal(gltf.scenes.length,0);assert.equal(s.children.length,0);assert.equal(associations.size,0);assert.equal(cleared,true);assert.equal(r.meshes[0].geometry,g);const out=new THREE.Group();out.add(...r.meshes);assert.equal(resolve(hit(out,2.2)),'b');});
