const assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const origin=process.env.SPLAT_TEST_ORIGIN||'http://127.0.0.1:8893';
function gaussianPLY(count=36){
 const properties=['x','y','z','nx','ny','nz','f_dc_0','f_dc_1','f_dc_2','opacity','scale_0','scale_1','scale_2','rot_0','rot_1','rot_2','rot_3'];
 const header=Buffer.from(`ply\nformat binary_little_endian 1.0\nelement vertex ${count}\n${properties.map(p=>'property float '+p).join('\n')}\nend_header\n`),data=Buffer.alloc(count*properties.length*4);
 for(let i=0;i<count;i++){const values=[(i%6-2.5)*.32,(Math.floor(i/6)-2.5)*.32,-3,0,0,0,1.3,.1,-.6,4,Math.log(.20),Math.log(.055),Math.log(.08),Math.cos(.3),0,0,Math.sin(.3)];values.forEach((v,j)=>data.writeFloatLE(v,(i*properties.length+j)*4));}return Buffer.concat([header,data]);
}
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});try{
 const page=await browser.newPage({viewport:{width:900,height:700}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const manifest={file:'synthetic.ply',mobileFile:'synthetic-mobile.ply',splatCount:36,mobileSplatCount:12,status:'experimental-trained',frame:'scan-y-up-metres',camera:{position:[0,0,0],quaternion:[0,0,0,1],fov:65},maxDistance:12};
 await page.route('**/splat-test/manifest.json',r=>r.fulfill({json:manifest}));await page.route('**/splat-test/synthetic.ply',r=>r.fulfill({body:gaussianPLY(),contentType:'application/octet-stream'}));
 await page.route('**/splat-test-host.html',r=>r.fulfill({contentType:'text/html',body:`<iframe style="width:100%;height:95vh;border:0" src="/scan-splat.html?manifest=splat-test/manifest.json"></iframe><script>window.messages=[];let epoch=1;addEventListener('message',e=>{messages.push(e.data);if(e.data.type==='grimes-camera-ready'||e.data.type==='grimes-claim-camera')e.source.postMessage({type:'grimes-camera-role',epoch:++epoch,driver:'scan',linked:true},location.origin)});</script>`}));
 await page.goto(origin+'/splat-test-host.html');const frame=page.frames().find(f=>f.url().includes('scan-splat.html'));await frame.waitForFunction(()=>window.splatInspection?.().state==='ready',null,{timeout:90000});
 let state=await frame.evaluate(()=>splatInspection());assert.equal(state.count,36);assert.equal(state.frame,'scan-y-up-metres');assert.equal(state.camera.identity,'scan');assert.equal(state.sharedMemory,false);assert.equal(state.pointCloudMode,false);assert.ok(await frame.locator('#experiment').isVisible());
 await page.waitForTimeout(500);await frame.locator('canvas').screenshot({path:'/tmp/grimes-splat-render.png'});
 const idleFrames=(await frame.evaluate(()=>splatInspection())).renderedFrames;await page.waitForTimeout(400);assert.equal((await frame.evaluate(()=>splatInspection())).renderedFrames,idleFrames,'settled idle view does not redraw');
 await page.mouse.move(400,300);await page.mouse.wheel(0,100);await page.waitForTimeout(350);const afterWheel=await frame.evaluate(()=>splatInspection());assert.ok(afterWheel.renderedFrames>idleFrames,'wheel redraws');assert.notEqual(afterWheel.camera.fov,65,'wheel updates FOV');await page.setViewportSize({width:940,height:720});await page.waitForTimeout(350);assert.ok((await frame.evaluate(()=>splatInspection())).renderedFrames>afterWheel.renderedFrames,'resize redraws');
 const canvas=frame.locator('canvas'),rect=await canvas.boundingBox();await page.mouse.click(rect.x+rect.width*.6,rect.y+rect.height*.6);await page.keyboard.down('w');await page.waitForTimeout(400);await page.keyboard.up('w');state=await frame.evaluate(()=>splatInspection());assert.ok(state.camera.position[2]<-.1,'W moves continuously in metres');
 await page.mouse.move(rect.x+400,rect.y+300);await page.mouse.down();await page.mouse.move(rect.x+450,rect.y+330,{steps:4});await page.mouse.up();assert.notDeepEqual((await frame.evaluate(()=>splatInspection())).camera.quaternion,[0,0,0,1]);
 await page.evaluate(()=>document.querySelector('iframe').contentWindow.postMessage({type:'grimes-camera-role',epoch:100,driver:'bim',linked:true},location.origin));
 const linked={position:[1,2,3],quaternion:[0,0,0,1],fov:70,zoom:1};await page.evaluate(p=>document.querySelector('iframe').contentWindow.postMessage({type:'grimes-linked-pose',epoch:100,pose:p},location.origin),linked);await page.waitForTimeout(100);assert.deepEqual((await frame.evaluate(()=>splatInspection())).camera.position,linked.position);
 await page.evaluate(()=>document.querySelector('iframe').contentWindow.postMessage({type:'grimes-linked-pose',epoch:99,pose:{position:[9,9,9],quaternion:[0,0,0,1],fov:70,zoom:1}},location.origin));await page.waitForTimeout(100);assert.deepEqual((await frame.evaluate(()=>splatInspection())).camera.position,linked.position,'stale pose ignored');
 await page.evaluate(()=>document.querySelector('iframe').contentWindow.postMessage({type:'grimes-linked-pose',epoch:100,pose:{position:[9,9,9],quaternion:[0,0,0,0],fov:70,zoom:1}},location.origin));await page.waitForTimeout(100);assert.deepEqual((await frame.evaluate(()=>splatInspection())).camera.position,linked.position,'invalid quaternion ignored');
 await page.screenshot({path:process.env.SPLAT_SCREENSHOT||'/tmp/grimes-splat-test.png'});assert.deepEqual(errors,[]);
 await page.goto(origin+'/scan-splat.html?manifest=https://example.com/manifest.json');await page.waitForFunction(()=>window.splatInspection?.().state==='error');assert.match(await page.locator('#loading').innerText(),/same-origin/);
 const mobile=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:2});await mobile.route('**/splat-test/manifest.json',r=>r.fulfill({json:{...manifest,splatCount:1500000}}));await mobile.route('**/splat-test/synthetic.ply',r=>r.fulfill({body:gaussianPLY(),contentType:'application/octet-stream'}));await mobile.route('**/splat-test/synthetic-mobile.ply',r=>r.fulfill({body:gaussianPLY(12),contentType:'application/octet-stream'}));await mobile.goto(origin+'/scan-splat.html?manifest=splat-test/manifest.json');await mobile.waitForFunction(()=>window.splatInspection?.().state==='ready');assert.equal((await mobile.evaluate(()=>splatInspection())).mobile,true);assert.equal((await mobile.evaluate(()=>splatInspection())).count,12,'mobile selects reduced derivative');const pad=await mobile.locator('[data-move=forward]').boundingBox();await mobile.mouse.move(pad.x+10,pad.y+10);await mobile.mouse.down();await mobile.waitForTimeout(350);await mobile.mouse.up();assert.ok((await mobile.evaluate(()=>splatInspection())).camera.position[2]<-.1,'mobile pad moves continuously');await mobile.close();
 console.log('PASS: idle/wheel/resize render scheduling, mobile derivative selection/budget, mobile pad, real 36-Gaussian PLY, scan frame, drag, continuous WASD, linked camera, stale/invalid rejection, same-origin guard, clean browser errors');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
