const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('fs'),vm=require('vm');
const source=fs.readFileSync(process.env.VIEWER || require('node:path').join(__dirname,'../grimes-bim-viewer.html'),'utf8');
function block(start,end){const a=source.indexOf(start); if(a<0)return '';return source.slice(a,source.indexOf(end,a));}
function fixture(){
 const dom=new Map();const get=id=>{if(!dom.has(id))dom.set(id,{style:{},classList:{add(){},remove(){}},innerHTML:'',textContent:''});return dom.get(id)};
 const ctx={document:{getElementById:get,body:{classList:{add(){}}}},console,window:{},Date,Number,highlight(){},unhighlightEquip(){},equipMeshes:[],equipMeta:{'123':{name:'test',type:'Receptacle',layer:'fixtures',isFedBy:['bmo:meter:77:kw']}},drawSpark(){},dsec:s=>s,drow:(k,v)=>k+':'+v,esc:String,revitRows(){return ''},EQUIP_LABELS:{},LAYERS:{fixtures:{json:'buildings/grimes/fixtures.elements.json'}},cachedJson:async()=>({meters:{}}),apportionRow(){return ''},carbonRows(){return ''},layerState:{},setTimeout,clearTimeout};
 vm.createContext(ctx);
 vm.runInContext(block('/* ELEMENT DATA HELPERS */','/* END ELEMENT DATA HELPERS */'),ctx);
 vm.runInContext(block('function neighbourRows(', '\nfunction apportionRow('),ctx);
 vm.runInContext(block('async function pickEquipment(', '\nfunction sumSeries('),ctx);
 return {ctx,get};
}
test('missing meter must not become LIVE zero',async()=>{const {ctx,get}=fixture();await ctx.pickEquipment({userData:{ids:['123']}},0);assert.notEqual(get('twinBadge').textContent,'LIVE');assert.doesNotMatch(get('twinBigKw').innerHTML,/0\.0/)});
test('actual zero remains available',async()=>{const {ctx,get}=fixture();ctx.cachedJson=async()=>({meters:{'77':{latest:{kw:0,t:new Date().toISOString()}}}});await ctx.pickEquipment({userData:{ids:['123']}},0);assert.match(get('twinBigKw').innerHTML,/0\.0/)});
test('line hit resolves without instanceId',async()=>{const {ctx}=fixture();await ctx.pickEquipment({userData:{ids:['123'],isLine:true}},undefined);assert.equal(ctx.equipPicked?.id,'123')});
test('late feed response cannot overwrite newly selected structure',async()=>{const {ctx,get}=fixture();let resolve;ctx.cachedJson=()=>new Promise(r=>resolve=r);const p=ctx.pickEquipment({userData:{ids:['123']}},0);ctx.equipMeta['456']={name:'column',type:'Column',system:'Structural'};await ctx.pickEquipment({userData:{ids:['456']}},0);resolve({meters:{'77':{latest:{kw:99}}}});await p;assert.equal(get('twinBadge').textContent,'NO FEED');assert.doesNotMatch(get('twinBigKw').innerHTML,/99/)});
test('CAD neighbours cannot cross known floors',()=>{const {ctx}=fixture();ctx.equipMeta={a:{type:'Pipe',level:'LEVEL 01'},b:{type:'Pipe',level:'LEVEL 02'},c:{type:'Pipe',level:'LEVEL 01'}};assert.doesNotMatch(ctx.neighbourRows('a',ctx.equipMeta.a),/selectElementById\('b'\)/);assert.match(ctx.neighbourRows('a',ctx.equipMeta.a),/selectElementById\('c'\)/)});
test('unknown floors do not imply co-location',()=>{const {ctx}=fixture();ctx.equipMeta={a:{type:'Pipe'},b:{type:'Pipe'}};assert.equal(ctx.neighbourRows('a',ctx.equipMeta.a),'')});
test('carbon converts cubic feet and refuses unknown units',()=>{const {ctx}=fixture();assert.equal(typeof ctx.volumeM3,'function');assert.ok(Math.abs(ctx.volumeM3('35.3146667 ft^3')-1)<1e-6);assert.equal(ctx.volumeM3('12 gallons'),null);assert.equal(ctx.volumeM3('-1 m3'),null)});
test('carbon needs material, nonnegative factor and evidence',()=>{const {ctx}=fixture();assert.equal(typeof ctx.carbonEstimate,'function');const info={volume:'2 m3',structural_material:'Steel'};assert.equal(ctx.carbonEstimate(info,{value:3,source:'EPD example',scope:'A1-A3'}),6);assert.equal(ctx.carbonEstimate(info,{value:3,source:'',scope:'A1-A3'}),null);assert.equal(ctx.carbonEstimate(info,{value:-3,source:'EPD',scope:'A1-A3'}),null);assert.equal(ctx.carbonEstimate({...info,structural_material:null},{value:3,source:'EPD',scope:'A1-A3'}),null)});
test('series totals align on timestamps, not positions',()=>{const {ctx}=fixture();const result=ctx.alignedMeterSeries([{timeseries_kw:[{t:'2026-01-01T00:00:00Z',v:2},{t:'2026-01-01T01:00:00Z',v:5}]},{timeseries_kw:[{t:'2026-01-01T01:00:00Z',v:10}]}]);assert.equal(result.length,1);assert.equal(result[0].v,15)});
test('late legacy equipment registry cannot overwrite an element panel',async()=>{const {ctx,get}=fixture();vm.runInContext(block('async function renderEquip(', '\n/* ══════════ BASELINE'),ctx);let resolve;ctx.cachedJson=()=>new Promise(r=>resolve=r);const pending=ctx.renderEquip('HVAC');get('twinDetEquip').innerHTML='current element neighbours';vm.runInContext('elementPickEpoch++',ctx);resolve({equipment:[]});await pending;assert.equal(get('twinDetEquip').innerHTML,'current element neighbours')});
test('BMO naive timestamp is interpreted in Pacific time',()=>{const {ctx}=fixture();assert.equal(typeof ctx.bmoTimestamp,'function');assert.equal(ctx.bmoTimestamp('2026-09-07 12:00:00'),Date.parse('2026-09-07T19:00:00Z'));assert.equal(ctx.bmoTimestamp('2026-01-07 12:00:00'),Date.parse('2026-01-07T20:00:00Z'));assert.ok(Number.isNaN(ctx.bmoTimestamp('2026-11-01 01:30:00')))});
test('same room label with conflicting floors is not confirmed co-location',()=>{const {ctx}=fixture();ctx.equipMeta={a:{location:'Room 1',levelKey:'L1'},b:{location:'Room 1',levelKey:'L2'}};assert.equal(ctx.neighbourRows('a',ctx.equipMeta.a),'')});
test('part assembly releases each decoded source before loading the next',async()=>{const {ctx}=fixture();assert.equal(typeof ctx.assembleElementParts,'function');let active=0,max=0;const out=await ctx.assembleElementParts(['a','b'],async id=>{max=Math.max(max,++active);return{id}},async p=>({meshes:[{id:p.id}],stats:{drawCalls:1,sourceTriangles:3,renderTriangles:3},identityBinding:{boundNodes:1}}),()=>active--);assert.equal(max,1);assert.equal(active,0);assert.equal(out.meshes.length,2);assert.equal(out.stats.sourceTriangles,6)});
test('part assembly releases a source when batching rejects',async()=>{const {ctx}=fixture();assert.equal(typeof ctx.assembleElementParts,'function');let active=0;await assert.rejects(()=>ctx.assembleElementParts(['a'],async()=>{active++;return{}},async()=>{throw Error('bad geometry')},()=>active--),/bad geometry/);assert.equal(active,0)});
